### ISSUE TITLE
Icon broken on Xfce (due to AppIndicator3?)

### ISSUE THREAD

**Issue by bharadwaj-raju** [SergKolo/lks-indicator#5]
On my fork (with just the change of a `--show-all` restored):

Without `--show-all`:

[![Without showall](http://i.imgur.com/WZMFpv0.png)](http://i.imgur.com/WZMFpv0.png)

[![Without showall, keys pressed](http://i.imgur.com/Vtgo6zN.png)](http://i.imgur.com/Vtgo6zN.png)

With `--show-all`:

[![No keys](http://i.imgur.com/hQnDQxM.png)](http://i.imgur.com/hQnDQxM.png)

[![pressed](http://i.imgur.com/MhRZfYc.png)](http://i.imgur.com/MhRZfYc.png)

System:
Xfce4 (Xubuntu 16.04), with Indicator Plugin and latest version of `lks-indicator`.

**Comment by SergKolo** [comment]
Changed the size of icons. Issue fixed as per conversation in askubuntu.com  chat
